'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Interfaces
    
    Partial Public Class DealerFileProcessedController_New
        
        '''<summary>
        '''ScriptManager1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
        
        '''<summary>
        '''Td1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Td1 As Global.System.Web.UI.HtmlControls.HtmlTableCell
        
        '''<summary>
        '''multipleDealerGrpDropControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents multipleDealerGrpDropControl As Global.Assurant.ElitaPlus.ElitaPlusWebApp.Common.MultipleColumnDDLabelControl_New
        
        '''<summary>
        '''rdParentFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdParentFile As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''lblParentFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblParentFile As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''TRPlanCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TRPlanCode As Global.System.Web.UI.HtmlControls.HtmlTableCell
        
        '''<summary>
        '''multipleDropControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents multipleDropControl As Global.Assurant.ElitaPlus.ElitaPlusWebApp.Common.MultipleColumnDDLabelControl_New
        
        '''<summary>
        '''rdDealerFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdDealerFile As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''moSearchResultsHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moSearchResultsHeader As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''moDataGrid_WRITE1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moDataGrid_WRITE1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''moDataGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moDataGrid As Global.System.Web.UI.WebControls.GridView
        
        '''<summary>
        '''dummybutton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dummybutton As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''mdlPopup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents mdlPopup As Global.AjaxControlToolkit.ModalPopupExtender
        
        '''<summary>
        '''pnlPopup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPopup As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''UpdatePanel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
        
        '''<summary>
        '''txtExtendedContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtExtendedContent As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''btnExtendedContentPopupCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnExtendedContentPopupCancel As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''moButtonPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moButtonPanel As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''BtnValidate_WRITE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BtnValidate_WRITE As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''BtnLoadCertificate_WRITE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BtnLoadCertificate_WRITE As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''BtnDeleteDealerFile_WRITE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BtnDeleteDealerFile_WRITE As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''BtnRejectReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BtnRejectReport As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''BtnErrorExport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BtnErrorExport As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''BtnProcessedExport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BtnProcessedExport As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''BtnGenerateResponse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BtnGenerateResponse As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''moUpLoadPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moUpLoadPanel As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''moFilenameLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moFilenameLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''dealerFileInput control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dealerFileInput As Global.System.Web.UI.HtmlControls.HtmlInputFile
        
        '''<summary>
        '''btnCopyDealerFile_WRITE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCopyDealerFile_WRITE As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''moExpectedFileLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moExpectedFileLabel As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''moExpectedFileLabel_NO_TRANSLATE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moExpectedFileLabel_NO_TRANSLATE As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''moInterfaceProgressControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moInterfaceProgressControl As Global.Assurant.ElitaPlus.ElitaPlusWebApp.Interfaces.InterfaceProgressControl
        
        '''<summary>
        '''btnAfterProgressBar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAfterProgressBar As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
