'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ReplacementOptions

    '''<summary>
    '''dvReplacementOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvReplacementOption As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblReplacmentOptionsr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReplacmentOptionsr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GVReplacementOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVReplacementOptions As Global.System.Web.UI.WebControls.GridView
End Class
