'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

#if DataEntities
Partial Public Class BillingDetail
         Inherits BaseEntity
         Implements ICertificateEntity, IRecordCreateModifyInfo 
    Public Property BillingDetailId As System.Guid

	Public Overrides ReadOnly Property Id As System.Guid
		Get
			Return BillingDetailId
		End Get
	End Property
    Public Property BillingHeaderId As System.Guid
    Public Property InstallmentNumber As Short
    Public Property BankOwnerName As String
    Public Property BilledAmount As Nullable(Of Decimal)
    Public Property Reason As String
    Public Property CreatedBy As String Implements IRecordCreateModifyInfo.CreatedBy
    Public Property CreatedDate As Date Implements IRecordCreateModifyInfo.CreatedDate
    Public Property ModifiedBy As String Implements IRecordCreateModifyInfo.ModifiedBy
    Public Property ModifiedDate As Nullable(Of Date) Implements IRecordCreateModifyInfo.ModifiedDate
    Public Property CertId As System.Guid
    Public Property PaymentRunDate As Date
    Public Property BankAcctNumber As String
    Public Property BankRtnNumber As String
    Public Property BillingStatusId As Nullable(Of System.Guid)
    Public Property RejectCodeId As Nullable(Of System.Guid)
    Public Property PaidId As Nullable(Of System.Guid)
    Public Property Tax As Nullable(Of Decimal)
    Public Property Commission As Nullable(Of Decimal)
    Public Property RejectedId As Nullable(Of System.Guid)
    Public Property NIGHTLY_PAYMENT_RUN_DATE As Nullable(Of Date)
    Public Property RE_ATTEMPT_COUNT As Nullable(Of Decimal)
    Public Property CREDIT_CARD_INFO_ID As Nullable(Of System.Guid)
    Public Property AuthorizationNumber As String
    Public Property MerchantCode As String
    Public Property InstallmentDueDate As Nullable(Of Date)
    Public Property RejectDate As Nullable(Of Date)
    Public Property RECON_INTERFACE_RUN_DATE As Nullable(Of Date)
    Public Property REFERENCE_RECORD As String
    Public Property DatePaidFor As Nullable(Of Date)
    Public Property PROCESSOR_REJECT_CODE As String

    Public Overridable Property Certificate As Certificate

End Class
#End If
