Public Class FlowSessionKeys

    Public Const SESSION_SERVICE_CENTER_ID As String = "SESSION_SERVICE_CENTER_ID"
    Public Const SESSION_SERVICE_CENTER As String = "SESSION_SERVICE_CENTER"
    Public Const SESSION_CERTIFICATE As String = "SESSION_CERTIFICATE"
    Public Const SESSION_CERTIFICATE_ITEM As String = "SESSION_CERTIFICATE_ITEM"
    Public Const SESSION_CERTIFICATE_COVERAGE As String = "SESSION_CERTIFICATE_COVERAGE"
    Public Const SESSION_CERTIFICATE_COVERAGE_ID As String = "SESSION_CERTIFICATE_COVERAGE_ID"
    Public Const SESSION_CERTIFICATE_ITEM_ID As String = "SESSION_CERTIFICATE_ITEM_ID"
    Public Const SESSION_CERT_REGISTERED_ITEM_ID As String = "SESSION_CERT_REGISTERED_ITEM_ID"
    Public Const SESSION_CERTIFICATE_ENDORSEMENT As String = "SESSION_CERTIFICATE_ENDORSEMENT"
    Public Const SESSION_CERTIFICATE_ENDORSE_ID As String = "SESSION_CERTIFICATE_ENDORSE_ID"
    Public Const SESSION_CERT_CANCELLATION As String = "SESSION_CERT_CANCELLATION"
    Public Const SESSION_CERTIFICATE_INSTALLMENT As String = "SESSION_CERTIFICATE_INSTALLMENT"
    Public Const SESSION_BANK_INFO As String = "SESSION_BANK_INFO"
    Public Const SESSION_LOCATE_SERVICE_CENTER_PARAMETERS As String = "SESSION_LOCATE_SERVICE_CENTER_PARAMETERS"

    Public Const SESSION_CLAIM As String = "SESSION_CLAIM"
    Public Const SESSION_CLAIM_ISSUE As String = "SESSION_CLAIM_ISSUE"
    Public Const SESSION_CLAIMED_EQUIPMENT As String = "SESSION_CLAIMED_EQUIPMENT"
    Public Const SESSION_OLD_CLAIM As String = "SESSION_OLD_CLAIM"
    Public Const SESSION_NEXT_SERVICEORDER As String = "SESSION_NEXT_SERVICEORDER"
    Public Const SESSION_PREV_SERVICEORDER As String = "SESSION_PREV_SERVICEORDER"
    Public Const SESSION_CLAIM_ISSUE_ID As String = "SESSION_CLAIM_ISSUE_ID"

    Public Const SESSION_ORIGINAL_SERVICE_CENTER_ID As String = "SESSION_ORIGINAL_SERVICE_CENTER_ID"
    Public Const SESSION_ORIGINAL_AUTHORIZED_AMOUNT As String = "SESSION_ORIGINAL_AUTHORIZED_AMOUNT"

    Public Const SESSION_SERVICE_ORDER As String = "SESSION_SERVICE_ORDER"
    Public Const SESSION_OLD_SERVICE_ORDER As String = "SESSION_OLD_SERVICE_ORDER"

    Public Const SESSION_CHANGES_MADE_FLAG As String = "SESSION_CHANGES_MADE_FLAG"

    Public Const SESSION_SOFTQUESTION_CERT_ID As String = "SESSION_SOFTQUESTION_CERT_ID"
    Public Const SESSION_SOFTQUESTION_COMMENTADDED As String = "SESSION_SOFTQUESTION_COMMENTADDED"

    Public Const SESSION_NEW_COMMENT As String = "SESSION_NEW_COMMENT"
    Public Const SESSION_MSTR_CLAIM_NUMB As String = "SESSION_MSTR_CLAIM_NUB"
    Public Const SESSION_DATE_OF_LOSS As String = "SESSION_DATE_OF_LOSS"
    Public Const SESSION_COMING_FROM_DENY_CLAIM As String = "SESSION_COMING_FROM_DENY_CLAIM"
    Public Const SESSION_RECOVERY_BUTTON_CLICK As String = "SESSION_RECOVERY_BUTTON_CLICK"
    Public Const SESSION_PAYMENT_METHOD As String = "SESSION_PAYMENT_METHOD"
    Public Const SESSION_DATE_CLAIM_REPORTED As String = "SESSION_DATE_CLAIM_REPORTED"

    Public Const SESSION_SHIPPING_INFO As String = "SHIPPING_INFO"

    Public Const SESSION_EMAIL_SENT As String = "SESSION_EMAIL_SENT"

    Public Const SESSION_CALLER_NAME As String = "SESSION_CALLER_NAME"
    Public Const SESSION_PROBLEM_DESCRIPTION As String = "SESSION_PROBLEM_DESCRIPTION"
    Public Const SESSION_IS_CUSTOMER_EMAIL As String = "SESSION_IS_CUSTOMER_EMAIL"
    Public Const SESSION_IS_SERVICE_CENTER_EMAIL As String = "SESSION_IS_SERVICE_CENTER_EMAIL"
    Public Const SESSION_IS_SALVAGE_CENTER_EMAIL As String = "SESSION_IS_SALVAGE_CENTER_EMAIL"
    Public Const SESSION_RISK_TYPE As String = "SESSION_RISK_TYPE"
    Public Const SESSION_COVERAGE_TYPE As String = "SESSION_COVERAGE_TYPE"
    Public Const SESSION_CERT_FIELD_NAME As String = "SESSION_CERT_FIELD_NAME"
    Public Const SESSION_CERT_FIELD_VALUE As String = "SESSION_CERT_FIELD_VALUE"



End Class
