'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UserControlContactInfo_New

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''moAddressTypeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moAddressTypeText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''moAddressTypeDrop_WRITE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moAddressTypeDrop_WRITE As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''moSalutationLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moSalutationLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''moSalutationText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moSalutationText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboSalutationId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSalutationId As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''moHomePhoneLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moHomePhoneLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''moHomePhoneText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moHomePhoneText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''moContactNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moContactNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''moContactNameText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moContactNameText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''moWorkPhoneLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moWorkPhoneLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''moWorkPhoneText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moWorkPhoneText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''moEmailAddressLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moEmailAddressLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''moEmailAddressText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moEmailAddressText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''moCellPhoneLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moCellPhoneLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''moCellPhoneText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moCellPhoneText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''moCompanyLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moCompanyLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''moCompanyText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moCompanyText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''moJobTitleLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moJobTitleLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''moJobTitleText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moJobTitleText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''moAddressController control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moAddressController As Global.Assurant.ElitaPlus.ElitaPlusWebApp.UserControlAddress_New
End Class
