'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Tables

    Partial Public Class ClaimStatusLetterForm

        '''<summary>
        '''EditPanel_WRITE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EditPanel_WRITE As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''multipleDealerDropControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents multipleDealerDropControl As Global.Assurant.ElitaPlus.ElitaPlusWebApp.Common.MultipleColumnDDLabelControl

        '''<summary>
        '''rbUseClaimStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbUseClaimStatus As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''rbUseGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbUseGroup As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''moClaimStatusLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moClaimStatusLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''moGroupIdLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moGroupIdLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ExtendedClaimStatusDropdownList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ExtendedClaimStatusDropdownList As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''cboGroupId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboGroupId As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''Mandatory1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Mandatory1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''moNotificationTypeLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moNotificationTypeLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cboNotificationTypeId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboNotificationTypeId As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''moActiveLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moActiveLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''IsActiveDropdownlList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents IsActiveDropdownlList As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''moLetterTypeLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moLetterTypeLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''moLetterTypeText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moLetterTypeText As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''moNumberOfDaysLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moNumberOfDaysLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''moNumberOfDaysText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moNumberOfDaysText As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''moSenderLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moSenderLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''moSenderText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moSenderText As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''moRecipientLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moRecipientLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''moRecipientText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moRecipientText As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''moServiceCenterRecipientLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moServiceCenterRecipientLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ServiceCenterRecipientDropdown control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ServiceCenterRecipientDropdown As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''moEmailSubjectLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moEmailSubjectLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''moEmailSubjectText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moEmailSubjectText As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''moEmailTextLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moEmailTextLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''HiddenSaveChangesPromptResponse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenSaveChangesPromptResponse As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''Panel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''Grid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Grid As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''HiddenDeletePromptResponse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenDeletePromptResponse As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''btnBack control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnBack As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnApply_WRITE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnApply_WRITE As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnUndo_WRITE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUndo_WRITE As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnNew_WRITE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnNew_WRITE As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCopy_WRITE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCopy_WRITE As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnDelete_WRITE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnDelete_WRITE As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
