'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Tables

    Partial Public Class ScheduleForm

        '''<summary>
        '''searchTable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents searchTable As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''moScheduleCodeLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moScheduleCodeLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''moScheduleDescriptionLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moScheduleDescriptionLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''moScheduleCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moScheduleCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''moScheduleDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moScheduleDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Div1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''Grid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Grid As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''BtnNew_WRITE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BtnNew_WRITE As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnBack control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnBack As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnApply_WRITE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnApply_WRITE As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnUndo_WRITE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUndo_WRITE As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnButtomNew_WRITE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnButtomNew_WRITE As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCopy_WRITE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCopy_WRITE As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''HiddenDeletePromptResponse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenDeletePromptResponse As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''HiddenSaveChangesPromptResponse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenSaveChangesPromptResponse As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    End Class
End Namespace
