'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace MexicoIShopService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ActualizaDatosInpunt", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ActualizaDatosInpunt
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PasswordField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DealerCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CertificateNumberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SKUField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BrandField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ModelField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SerialNumberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IMEIField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReplacementBrandField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReplacementModelField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReplacementSerialNumberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReplacementIMEIField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReplacementSKUField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TransactionTypeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdMotiveField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property UserId() As String
            Get
                Return Me.UserIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserIdField, value) <> true) Then
                    Me.UserIdField = value
                    Me.RaisePropertyChanged("UserId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property Password() As String
            Get
                Return Me.PasswordField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PasswordField, value) <> true) Then
                    Me.PasswordField = value
                    Me.RaisePropertyChanged("Password")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property DealerCode() As String
            Get
                Return Me.DealerCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DealerCodeField, value) <> true) Then
                    Me.DealerCodeField = value
                    Me.RaisePropertyChanged("DealerCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property CertificateNumber() As String
            Get
                Return Me.CertificateNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CertificateNumberField, value) <> true) Then
                    Me.CertificateNumberField = value
                    Me.RaisePropertyChanged("CertificateNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property SKU() As String
            Get
                Return Me.SKUField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SKUField, value) <> true) Then
                    Me.SKUField = value
                    Me.RaisePropertyChanged("SKU")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property Brand() As String
            Get
                Return Me.BrandField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BrandField, value) <> true) Then
                    Me.BrandField = value
                    Me.RaisePropertyChanged("Brand")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property Model() As String
            Get
                Return Me.ModelField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ModelField, value) <> true) Then
                    Me.ModelField = value
                    Me.RaisePropertyChanged("Model")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Property SerialNumber() As String
            Get
                Return Me.SerialNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SerialNumberField, value) <> true) Then
                    Me.SerialNumberField = value
                    Me.RaisePropertyChanged("SerialNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public Property IMEI() As String
            Get
                Return Me.IMEIField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IMEIField, value) <> true) Then
                    Me.IMEIField = value
                    Me.RaisePropertyChanged("IMEI")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=9)>  _
        Public Property ReplacementBrand() As String
            Get
                Return Me.ReplacementBrandField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReplacementBrandField, value) <> true) Then
                    Me.ReplacementBrandField = value
                    Me.RaisePropertyChanged("ReplacementBrand")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public Property ReplacementModel() As String
            Get
                Return Me.ReplacementModelField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReplacementModelField, value) <> true) Then
                    Me.ReplacementModelField = value
                    Me.RaisePropertyChanged("ReplacementModel")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=11)>  _
        Public Property ReplacementSerialNumber() As String
            Get
                Return Me.ReplacementSerialNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReplacementSerialNumberField, value) <> true) Then
                    Me.ReplacementSerialNumberField = value
                    Me.RaisePropertyChanged("ReplacementSerialNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=12)>  _
        Public Property ReplacementIMEI() As String
            Get
                Return Me.ReplacementIMEIField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReplacementIMEIField, value) <> true) Then
                    Me.ReplacementIMEIField = value
                    Me.RaisePropertyChanged("ReplacementIMEI")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=13)>  _
        Public Property ReplacementSKU() As String
            Get
                Return Me.ReplacementSKUField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReplacementSKUField, value) <> true) Then
                    Me.ReplacementSKUField = value
                    Me.RaisePropertyChanged("ReplacementSKU")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=14)>  _
        Public Property TransactionType() As String
            Get
                Return Me.TransactionTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TransactionTypeField, value) <> true) Then
                    Me.TransactionTypeField = value
                    Me.RaisePropertyChanged("TransactionType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=15)>  _
        Public Property IdMotive() As String
            Get
                Return Me.IdMotiveField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdMotiveField, value) <> true) Then
                    Me.IdMotiveField = value
                    Me.RaisePropertyChanged("IdMotive")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ActualizaDatosOutput", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ActualizaDatosOutput
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MensajeField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Codigo() As String
            Get
                Return Me.CodigoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodigoField, value) <> true) Then
                    Me.CodigoField = value
                    Me.RaisePropertyChanged("Codigo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Mensaje() As String
            Get
                Return Me.MensajeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MensajeField, value) <> true) Then
                    Me.MensajeField = value
                    Me.RaisePropertyChanged("Mensaje")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="MexicoIShopService.SwitchUpAppleSoap")>  _
    Public Interface SwitchUpAppleSoap
        
        'CODEGEN: Generating message contract since element name input from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ActualizaDatos", ReplyAction:="*")>  _
        Function ActualizaDatos(ByVal request As MexicoIShopService.ActualizaDatosRequest) As MexicoIShopService.ActualizaDatosResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ActualizaDatos", ReplyAction:="*")>  _
        Function ActualizaDatosAsync(ByVal request As MexicoIShopService.ActualizaDatosRequest) As System.Threading.Tasks.Task(Of MexicoIShopService.ActualizaDatosResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ActualizaDatosRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ActualizaDatos", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As MexicoIShopService.ActualizaDatosRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As MexicoIShopService.ActualizaDatosRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ActualizaDatosRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public input As MexicoIShopService.ActualizaDatosInpunt
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal input As MexicoIShopService.ActualizaDatosInpunt)
            MyBase.New
            Me.input = input
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ActualizaDatosResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ActualizaDatosResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As MexicoIShopService.ActualizaDatosResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As MexicoIShopService.ActualizaDatosResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ActualizaDatosResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ActualizaDatosResult As MexicoIShopService.ActualizaDatosOutput
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ActualizaDatosResult As MexicoIShopService.ActualizaDatosOutput)
            MyBase.New
            Me.ActualizaDatosResult = ActualizaDatosResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface SwitchUpAppleSoapChannel
        Inherits MexicoIShopService.SwitchUpAppleSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SwitchUpAppleSoapClient
        Inherits System.ServiceModel.ClientBase(Of MexicoIShopService.SwitchUpAppleSoap)
        Implements MexicoIShopService.SwitchUpAppleSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MexicoIShopService_SwitchUpAppleSoap_ActualizaDatos(ByVal request As MexicoIShopService.ActualizaDatosRequest) As MexicoIShopService.ActualizaDatosResponse Implements MexicoIShopService.SwitchUpAppleSoap.ActualizaDatos
            Return MyBase.Channel.ActualizaDatos(request)
        End Function
        
        Public Function ActualizaDatos(ByVal input As MexicoIShopService.ActualizaDatosInpunt) As MexicoIShopService.ActualizaDatosOutput
            Dim inValue As MexicoIShopService.ActualizaDatosRequest = New MexicoIShopService.ActualizaDatosRequest()
            inValue.Body = New MexicoIShopService.ActualizaDatosRequestBody()
            inValue.Body.input = input
            Dim retVal As MexicoIShopService.ActualizaDatosResponse = CType(Me,MexicoIShopService.SwitchUpAppleSoap).ActualizaDatos(inValue)
            Return retVal.Body.ActualizaDatosResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MexicoIShopService_SwitchUpAppleSoap_ActualizaDatosAsync(ByVal request As MexicoIShopService.ActualizaDatosRequest) As System.Threading.Tasks.Task(Of MexicoIShopService.ActualizaDatosResponse) Implements MexicoIShopService.SwitchUpAppleSoap.ActualizaDatosAsync
            Return MyBase.Channel.ActualizaDatosAsync(request)
        End Function
        
        Public Function ActualizaDatosAsync(ByVal input As MexicoIShopService.ActualizaDatosInpunt) As System.Threading.Tasks.Task(Of MexicoIShopService.ActualizaDatosResponse)
            Dim inValue As MexicoIShopService.ActualizaDatosRequest = New MexicoIShopService.ActualizaDatosRequest()
            inValue.Body = New MexicoIShopService.ActualizaDatosRequestBody()
            inValue.Body.input = input
            Return CType(Me,MexicoIShopService.SwitchUpAppleSoap).ActualizaDatosAsync(inValue)
        End Function
    End Class
End Namespace
