'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

#if DataEntities
Partial Public Class CoverageLoss
         Inherits BaseEntity
         Implements ICompanyGroupEntity, IRecordCreateModifyInfo 
    Public Property CoverageLossId As System.Guid

	Public Overrides ReadOnly Property Id As System.Guid
		Get
			Return CoverageLossId
		End Get
	End Property
    Public Property CompanyGroupId As System.Guid
    Public Property CoverageTypeId As System.Guid
    Public Property CauseOfLossId As System.Guid
    Public Property CreatedBy As String Implements IRecordCreateModifyInfo.CreatedBy
    Public Property CreatedDate As Date Implements IRecordCreateModifyInfo.CreatedDate
    Public Property ModifiedBy As String Implements IRecordCreateModifyInfo.ModifiedBy
    Public Property ModifiedDate As Nullable(Of Date) Implements IRecordCreateModifyInfo.ModifiedDate
    Public Property DefaultFlag As String
    Public Property Active As String

    Public Overridable Property ELP_COMPANY_GROUP As CompanyGroup

End Class
#End If
