Public Enum FulfillmentProviderType As Integer
    <Xcd("FULFILLMENT_PROVIDER", "V1_SINGLE_AUTH")> V1 = 0
    <Xcd("FULFILLMENT_PROVIDER", "V2_ORACLE_EBS")> V2 = 2
    <Xcd("FULFILLMENT_PROVIDER", "V3_ELITA_CLAIM_FULFILLMENT")> V3 = 3
    <Xcd("FULFILLMENT_PROVIDER", "V4_DYNAMIC_FULFILLMENT")> V4 = 1
End Enum