'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

#if DataEntities
Partial Public Class List
         Inherits BaseEntity
         Implements ICommonEntity, IRecordCreateModifyInfo 
    Public Property ListId As System.Guid

	Public Overrides ReadOnly Property Id As System.Guid
		Get
			Return ListId
		End Get
	End Property
    Public Property MaintainableByUser As String
    Public Property DictionaryItemId As System.Guid
    Public Property Code As String
    Public Property CreatedDate As Date Implements IRecordCreateModifyInfo.CreatedDate
    Public Property ModifiedDate As Nullable(Of Date) Implements IRecordCreateModifyInfo.ModifiedDate
    Public Property CreatedBy As String Implements IRecordCreateModifyInfo.CreatedBy
    Public Property ModifiedBy As String Implements IRecordCreateModifyInfo.ModifiedBy
    Public Property ActiveFlag As String
    Public Property ExcludeByRole As String

    Public Overridable Property DictionaryItem As DictionaryItem
    Public Overridable Property ListItems As ICollection(Of ListItem) = New HashSet(Of ListItem)

End Class
#End If
