'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

#if DataEntities
Partial Public Class ServiceCenter
         Inherits BaseEntity
         Implements ICountryEntity, IRecordCreateModifyInfo 
    Public Property ServiceCenterId As System.Guid

	Public Overrides ReadOnly Property Id As System.Guid
		Get
			Return ServiceCenterId
		End Get
	End Property
    Public Property ADDRESS_ID As System.Guid
    Public Property SERVICE_GROUP_ID As System.Guid
    Public Property LOANER_CENTER_ID As Nullable(Of System.Guid)
    Public Property MASTER_CENTER_ID As Nullable(Of System.Guid)
    Public Property CODE As String
    Public Property DESCRIPTION As String
    Public Property RATING_CODE As String
    Public Property CONTACT_NAME As String
    Public Property OWNER_NAME As String
    Public Property PHONE1 As String
    Public Property PHONE2 As String
    Public Property FAX As String
    Public Property EMAIL As String
    Public Property FTP_ADDRESS As String
    Public Property TAX_ID As String
    Public Property SERVICE_WARRANTY_DAYS As Short
    Public Property STATUS_CODE As String
    Public Property BUSINESS_HOURS As String
    Public Property MASTER_FLAG As String
    Public Property LOANER_FLAG As String
    Public Property DEFAULT_TO_EMAIL_FLAG As String
    Public Property IVA_RESPONSIBLE_FLAG As String
    Public Property CreatedBy As String Implements IRecordCreateModifyInfo.CreatedBy
    Public Property CreatedDate As Date Implements IRecordCreateModifyInfo.CreatedDate
    Public Property ModifiedBy As String Implements IRecordCreateModifyInfo.ModifiedBy
    Public Property ModifiedDate As Nullable(Of Date) Implements IRecordCreateModifyInfo.ModifiedDate
    Public Property COUNTRY_ID As System.Guid
    Public Property COMMENTS As String
    Public Property BankInfoId As Nullable(Of System.Guid)
    Public Property PAYMENT_METHOD_ID As Nullable(Of System.Guid)
    Public Property SHIPPING As String
    Public Property PROCESSING_FEE As Nullable(Of Decimal)
    Public Property CC_EMAIL As String
    Public Property ORIGINALDEALERID As Nullable(Of System.Guid)
    Public Property ROUTE_ID As Nullable(Of System.Guid)
    Public Property INTEGRATED_WITH_ID As Nullable(Of System.Guid)
    Public Property PAY_MASTER As String
    Public Property INTEGRATED_AS_OF As Nullable(Of Date)
    Public Property FREE_ZONE_FLAG As String
    Public Property REVERSE_LOGISTICS_ID As System.Guid
    Public Property SERVICE_LEVEL_GROUP_ID_OLD As Nullable(Of System.Guid)
    Public Property DISTRIBUTION_METHOD_ID As Nullable(Of System.Guid)
    Public Property FULFILLMENT_TIME_ZONE_ID As Nullable(Of System.Guid)
    Public Property PRICE_LIST_CODE As String
    Public Property DISCOUNT_PCT As Nullable(Of Decimal)
    Public Property DISCOUNT_DAYS As Nullable(Of Short)
    Public Property NET_DAYS As Nullable(Of Short)
    Public Property PRICE_GROUP_ID_OLD As Nullable(Of System.Guid)
    Public Property PRE_INVOICE_ID As System.Guid

    Public Overridable Property Country As Country
    Public Overridable Property Servicecenter1 As ICollection(Of ServiceCenter) = New HashSet(Of ServiceCenter)
    Public Overridable Property ServiceCenter2 As ServiceCenter
    Public Overridable Property ServiceCenter3 As ServiceCenter
    Public Overridable Property BankInfo As BankInfo

End Class
#End If
