'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Reports

    Partial Public Class AMLComplianceReportForm

        '''<summary>
        '''moBaseReportOnLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moBaseReportOnLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rdPeriod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdPeriod As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''moBeginDateLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moBeginDateLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''moBeginDateText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moBeginDateText As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnBeginDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnBeginDate As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''moEndDateLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moEndDateLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''moEndDateText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moEndDateText As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnEndDate As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''moReportTypeLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moReportTypeLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''chkAllCerts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAllCerts As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkPepReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkPepReport As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkTerrReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkTerrReport As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkSusOpReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSusOpReport As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''moSortByLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moSortByLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rdReportSortOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdReportSortOrder As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''btnGenRpt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnGenRpt As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
