'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Reports
    
    Partial Public Class ClaimEventCountPerCertificateReportForm
        
        '''<summary>
        '''lblDealerGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDealerGroup As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''ddlcDealerGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlcDealerGroup As Global.Assurant.ElitaPlus.ElitaPlusWebApp.Common.MultipleColumnDDLabelControl_New
        
        '''<summary>
        '''lblDealers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDealers As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''ucDealerAvaSel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucDealerAvaSel As Global.Assurant.ElitaPlus.ElitaPlusWebApp.Generic.UserControlAvailableSelected_New
        
        '''<summary>
        '''lblDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDate As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''moDateText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moDateText As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''BtnDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BtnDate As Global.System.Web.UI.WebControls.ImageButton
        
        '''<summary>
        '''lblRepairedClaims control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRepairedClaims As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''moRepairedClaimsText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moRepairedClaimsText As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblAndOr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAndOr As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblReplacedClaims control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReplacedClaims As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''moReplacedClaimsText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moReplacedClaimsText As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''btnGenRpt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnGenRpt As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
