'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Reports

    Partial Public Class ExtendedStatusAgingReportForm

        '''<summary>
        '''Tr1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Tr1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''Label2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rDealer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rDealer As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''moDealerLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moDealerLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cboDealer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboDealer As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''Tr2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Tr2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblAllStages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAllStages As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rbStages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbStages As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''lblStageName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStageName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''moStageList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moStageList As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''Tr3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Tr3 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblAllStageStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAllStageStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rbStageStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbStageStatus As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''lblStageStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStageStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''moStageStatusList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moStageStatusList As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''Tr4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Tr4 As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''lblNoofDayssincestageopened control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNoofDayssincestageopened As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''tbdayssincestageopened control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbdayssincestageopened As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnGenRpt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnGenRpt As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
