'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Reports
    
    Partial Public Class IssuedCancelledRegisterwithPremium
        
        '''<summary>
        '''Td2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Td2 As Global.System.Web.UI.HtmlControls.HtmlTableCell
        
        '''<summary>
        '''moUserCompanyMultipleDrop control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moUserCompanyMultipleDrop As Global.Assurant.ElitaPlus.ElitaPlusWebApp.Common.MultipleColumnDDLabelControl_New
        
        '''<summary>
        '''Tr2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Tr2 As Global.System.Web.UI.HtmlControls.HtmlTableRow
        
        '''<summary>
        '''lblMonth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMonth As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''moMonthList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moMonthList As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''lblYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblYear As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''moYearList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moYearList As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''Tr4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Tr4 As Global.System.Web.UI.HtmlControls.HtmlTableRow
        
        '''<summary>
        '''rdealer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdealer As Global.System.Web.UI.WebControls.RadioButton
        
        '''<summary>
        '''Td1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Td1 As Global.System.Web.UI.HtmlControls.HtmlTableCell
        
        '''<summary>
        '''moDealerMultipleDrop control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moDealerMultipleDrop As Global.Assurant.ElitaPlus.ElitaPlusWebApp.Common.MultipleColumnDDLabelControl_New
        
        '''<summary>
        '''Tr1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Tr1 As Global.System.Web.UI.HtmlControls.HtmlTableRow
        
        '''<summary>
        '''lblReportOptionList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReportOptionList As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''moReportOptionList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moReportOptionList As Global.System.Web.UI.WebControls.RadioButtonList
        
        '''<summary>
        '''btnGenRpt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnGenRpt As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
