'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Claims
    
    Partial Public Class ClaimFollowUpListForm
        
        '''<summary>
        '''ScriptManager1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
        
        '''<summary>
        '''searchTable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents searchTable As Global.System.Web.UI.HtmlControls.HtmlTable
        
        '''<summary>
        '''LabelSearchClaimNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSearchClaimNumber As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''LabelSearchCustomerName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSearchCustomerName As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''LabelSearchClaimExtendedStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSearchClaimExtendedStatus As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''TextBoxSearchClaimNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxSearchClaimNumber As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''TextBoxSearchCustomerName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxSearchCustomerName As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''moClaimExtendedStatusDD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moClaimExtendedStatusDD As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''LabelSearchServiceCenter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSearchServiceCenter As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''LabelSearchClaimAdjuster control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSearchClaimAdjuster As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblOwner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOwner As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''moServiceCenterText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moServiceCenterText As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''TextBoxSearchClaimAdjuster control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxSearchClaimAdjuster As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''moOwnerDD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moOwnerDD As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''LabelFollowUpDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelFollowUpDate As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblClaimStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblClaimStatus As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''LabelSearchClaimTATRange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSearchClaimTATRange As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''TextBoxFollowUpDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBoxFollowUpDate As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''BtnFollowUpDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BtnFollowUpDate As Global.System.Web.UI.WebControls.ImageButton
        
        '''<summary>
        '''cboClaimStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboClaimStatus As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''moClaimTATRangeDD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moClaimTATRangeDD As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''lblSearchSortBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSearchSortBy As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''LabelSearchDealer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSearchDealer As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''LabelSearchLastActivity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelSearchLastActivity As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''cboSortBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboSortBy As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''moDealerDrop control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moDealerDrop As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''moLastActivityDD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents moLastActivityDD As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''Label control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''cboNonOperatedClaims control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboNonOperatedClaims As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''btnClearSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnClearSearch As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''trPageSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trPageSize As Global.System.Web.UI.HtmlControls.HtmlTableRow
        
        '''<summary>
        '''lblPageSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPageSize As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''Label3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''cboPageSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboPageSize As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''lblRecordCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRecordCount As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''Grid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Grid As Global.System.Web.UI.WebControls.DataGrid
    End Class
End Namespace
