'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UserControlClaimInfo
    
    '''<summary>
    '''CertificateNumberLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CertificateNumberLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CertificateNumberTD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CertificateNumberTD As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''ServiceCenterLabelTD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ServiceCenterLabelTD As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''ServiceCenterNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ServiceCenterNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ServiceCenterTD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ServiceCenterTD As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''StatusLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CLAIMStatusTD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CLAIMStatusTD As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''SubscriberStatusLabelTD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubscriberStatusLabelTD As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''SubscriberStatusLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubscriberStatusLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SubscriberStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubscriberStatus As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''ScrutinyRequiredLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScrutinyRequiredLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ScrutinyRequiredLabelTD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScrutinyRequiredLabelTD As Global.System.Web.UI.HtmlControls.HtmlTableCell
End Class
