'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WorkQueueForm
    
    '''<summary>
    '''moMessageController control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moMessageController As Global.Assurant.ElitaPlus.ElitaPlusWebApp.MessageController
    
    '''<summary>
    '''DeleteButtonId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteButtonId As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''DeleteButtonArgument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteButtonArgument As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''lblModalTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Img1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Img1 As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''imgMsgIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgMsgIcon As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''tdModalMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdModalMessage As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''lblCancelMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCancelMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tdBtnArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdBtnArea As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''btnModalCancelYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnModalCancelYes As Global.System.Web.UI.HtmlControls.HtmlInputButton
    
    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.HtmlControls.HtmlInputButton
    
    '''<summary>
    '''moWorkQueueNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moWorkQueueNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''moWorkQueueName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moWorkQueueName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''moCompanyLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moCompanyLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''moCompanyDropDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moCompanyDropDown As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''moCompanyText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moCompanyText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''moTimeZoneLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moTimeZoneLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''moTimeZoneDropDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moTimeZoneDropDown As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''moTimeZoneText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moTimeZoneText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''moEffectiveDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moEffectiveDateLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''moEffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moEffectiveDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnEffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEffectiveDate As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''moExpirationDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moExpirationDateLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''moExpirationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moExpirationDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnExpirationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExpirationDate As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''moStartItemDelayMinutesLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moStartItemDelayMinutesLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''moStartItemDelayMinutes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moStartItemDelayMinutes As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''moTimeToCompleteMinutesLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moTimeToCompleteMinutesLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''moTimeToCompleteMinutes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moTimeToCompleteMinutes As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''moWorkQueueTypeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moWorkQueueTypeLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''moWorkQueueTypeDropDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moWorkQueueTypeDropDown As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''moWorkQueueTypeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moWorkQueueTypeText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''moAdminRoleLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moAdminRoleLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''moAdminRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moAdminRole As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''moActionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moActionLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''moActionDropDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moActionDropDown As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''moActionText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moActionText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''moTransformationFileLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moTransformationFileLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''moTransformationFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moTransformationFile As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''moLockableDataTypeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moLockableDataTypeLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''moLockableDataType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moLockableDataType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''moMaximumReQueueLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moMaximumReQueueLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''moMaximumReQueue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moMaximumReQueue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''moReQueueDelayLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moReQueueDelayLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''moReQueueDelay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moReQueueDelay As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''hdnSelectedTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSelectedTab As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnDisabledTabs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnDisabledTabs As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label8 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''moSchedulesPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moSchedulesPage As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''GridViewSchedules control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewSchedules As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btnAddNewSchedule_WRITE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddNewSchedule_WRITE As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''moReQueueReasonsPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moReQueueReasonsPage As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''GridViewReQueueReasons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewReQueueReasons As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btnAddNewReQueueReason_WRITE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddNewReQueueReason_WRITE As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''moReDirectReasonsPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents moReDirectReasonsPage As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''GridViewReDirectReasons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewReDirectReasons As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btnAddNewReDirectReason_WRITE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddNewReDirectReason_WRITE As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBack As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSave_WRITE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave_WRITE As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCopy_WRITE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCopy_WRITE As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnNew_WRITE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNew_WRITE As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnUndo_Write control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUndo_Write As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDelete_WRITE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete_WRITE As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''HiddenSaveChangesPromptResponse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenSaveChangesPromptResponse As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
