'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Certificates
    
    Partial Public Class CheckRejectPaymentForm
        
        '''<summary>
        '''ScriptManager1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
        
        '''<summary>
        '''LabelTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelTitle As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblCheckRejectedOn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCheckRejectedOn As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtCheckRejectedOn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCheckRejectedOn As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''ImageButtonCheckRejectedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ImageButtonCheckRejectedDate As Global.System.Web.UI.WebControls.ImageButton
        
        '''<summary>
        '''lblSltRejectedChk control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSltRejectedChk As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtSltRejectedChk control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSltRejectedChk As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lblRejectReason control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRejectReason As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''ddlRejectReason control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlRejectReason As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''lblCheckComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCheckComments As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtCheckComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCheckComments As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''btnAdd_WRITE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAdd_WRITE As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnBack control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnBack As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''HiddenSaveChangesPromptResponse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HiddenSaveChangesPromptResponse As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    End Class
End Namespace
